### Affine/Softmax 순전파 & 역전파


In [1]:
import numpy as np 

In [5]:
x = np.random.rand(2,2)
w = np.random.rand(2,3)
result = np.dot(x,w)
b = np.random.rand(3)

print(x,x.shape)
print(w, w.shape)
print(result, result.shape)
print(b, b.shape)

[[0.35349765 0.67616949]
 [0.10260269 0.0992621 ]] (2, 2)
[[0.79045881 0.57392484 0.41013021]
 [0.46727912 0.87394405 0.48190783]] (2, 3)
[[0.59538521 0.79381538 0.47083144]
 [0.12748631 0.14563575 0.08991564]] (2, 3)
[0.12974405 0.52064067 0.38176506] (3,)


In [2]:
x = np.random.rand(2)
w = np.random.rand(2,3)
b = np.random.rand(3)

print(x,x.shape)
print(w, w.shape)
print(b, b.shape)

[0.60167803 0.36783849] (2,)
[[0.61770655 0.28791988 0.3156443 ]
 [0.84759521 0.42568432 0.63525221]] (2, 3)
[0.86441089 0.23970605 0.21987286] (3,)
