### Affine 순전파 & 역전파


In [1]:
import numpy as np 

In [5]:
x = np.random.rand(2,2)
w = np.random.rand(2,3)
result = np.dot(x,w)
b = np.random.rand(3)

print(x,x.shape)
print(w, w.shape)
print(result, result.shape)
print(b, b.shape)

[[0.35349765 0.67616949]
 [0.10260269 0.0992621 ]] (2, 2)
[[0.79045881 0.57392484 0.41013021]
 [0.46727912 0.87394405 0.48190783]] (2, 3)
[[0.59538521 0.79381538 0.47083144]
 [0.12748631 0.14563575 0.08991564]] (2, 3)
[0.12974405 0.52064067 0.38176506] (3,)


In [2]:
x = np.random.rand(2)
w = np.random.rand(2,3)
b = np.random.rand(3)

print(x,x.shape)
print(w, w.shape)
print(b, b.shape)

[0.60167803 0.36783849] (2,)
[[0.61770655 0.28791988 0.3156443 ]
 [0.84759521 0.42568432 0.63525221]] (2, 3)
[0.86441089 0.23970605 0.21987286] (3,)


In [7]:
x = np.random.rand(3,)
y = np.random.rand(3,1)
z = np.random.rand(1,3)
print(x, x.shape)
print(y, y.shape)
print(z, z.shape)

[0.10303939 0.78895066 0.13667582] (3,)
[[0.86997449]
 [0.04111377]
 [0.89734416]] (3, 1)
[[0.63568962 0.92314442 0.63220714]] (1, 3)


In [8]:
class Affine:
    def __init__(self, w, b):
        self.w = w 
        self.b = b
        self.x = None 
        self.dw = None 
        self.db = None 
        
    def forward(self, x):
        self.x = x 
        out = np.dot(x, self.w) + self.b 
        return out 
    
    def backward(self, dout):
        dx = np.dot(dout, self.w.T) # 여기서 대문자 'T'는 전치행렬을 뜻함, 혹은 np.transpose(w) 또는 np.swapaxes(w,0,1)로 정의 가능 
        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        

### 소프트맥스 함수 순전파 & 역전파

In [10]:
def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x-c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x/sum_exp_x
    
    return y

def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t*np.log(y+delta))


class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None # loss
        self.y = None # output of softmax function
        self.t = None # One-hot vector answer label
        
    def forward(self, x, t):
        self.t = t 
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss 
    
    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size 
        
        return dx 