In [2]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split 

### Split Data

- 데이터를 x_train, y_train, x_test, y_test로 나누는 방법 실습

In [5]:
# 먼저 zip()을 사용한 방법
x,y = zip([1,'a'],[2,'b'],[3,'c'])
print(x)
print(y)

(1, 2, 3)
('a', 'b', 'c')


In [6]:
tmp = [['jack', 3], ['kay',11],['kim',5]]
x,y = zip(*tmp)
print(x)
print(y)

('jack', 'kay', 'kim')
(3, 11, 5)


In [8]:
# 데이터 프레임을 사용하여 분리
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [10]:
# 데이터프레임은 열의 이름으로 각 열에 접근 가능
# 이를 통해 x와 y 데이터를 쉽게 분리할 수 있음
x,y = df['메일 본문'], df['스팸 메일 유무']
print(x.tolist())
print(y.tolist())

['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
[1, 0, 0, 1]


In [11]:
# 넘파이를 이용하여 분리
np_array = np.arange(0,16).reshape((4,4))
print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
x = np_array[:, :3] # 마지막 열만 제외하고 x
y = np_array[:,3] # 마지막 열만 y
print(x)
print(y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[ 3  7 11 15]


In [15]:
# 사이킷 런을 이용하여 분리
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=1234)
'''
X : 독립 변수 데이터. (배열이나 데이터프레임)
y : 종속 변수 데이터. 레이블 데이터.
test_size : 테스트용 데이터 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.
train_size : 학습용 데이터의 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.
random_state : 난수 시드
'''

'\nX : 독립 변수 데이터. (배열이나 데이터프레임)\ny : 종속 변수 데이터. 레이블 데이터.\ntest_size : 테스트용 데이터 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.\ntrain_size : 학습용 데이터의 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.\nrandom_state : 난수 시드\n'

In [17]:
x, y = np.arange(10).reshape((5,2)) , range(5)
print(x)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [20]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state=1234)

In [19]:
print(x_train)
print(x_test)

[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[0 1 2]]


In [21]:
print(y_train)
print(y_test)

[1, 2, 3]
[4, 0]


In [25]:
# random state의 값을 변경하여 진행
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state=1)

In [26]:
print(x_train)
print(x_test)

[[8 9]
 [0 1]
 [6 7]]
[[4 5]
 [2 3]]


In [27]:
print(y_train)
print(y_test)

[4, 0, 3]
[2, 1]
