In [2]:
import numpy as np 

c= np.array([[1,0,0,0,0,0,0]])
W = np.random.randn(7,3)
h = np.matmul(c,W)
print(W)
print(h)

[[-1.12220018  0.10847743 -1.38103142]
 [ 2.19010675  1.14136637 -0.46682956]
 [-0.20403903 -1.87331293 -1.27574156]
 [ 0.75602748 -0.65024005 -0.83220733]
 [ 1.73752952  0.22567256 -0.59049944]
 [-1.04225394  1.01108333 -0.66054859]
 [ 0.06361437 -0.44961561 -0.76429509]]
[[-1.12220018  0.10847743 -1.38103142]]
