### 기초 텐서 실습

In [1]:
import numpy as np

### 0차원

In [18]:
# 0차원
d = np.array(5)
print(d)
print(d.ndim) # axis의 개수 or 텐서의 차원
print(d.shape) # 텐서의 크기

5
0
()


### 1차원

In [20]:
d = np.array([1, 2, 3, 4])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 1
텐서의 크기(shape) : (4,)


- 1차원 텐서이지만

    - 텐서에서의 차원은 축의 개수

- 4차원 벡터이다

    - 벡터에서의 차원은 하나의 축에 놓인 원소의 개수

### 2차원

In [21]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


- 행과 열이 존재하는 벡터의 배열, 행렬(Matrix)을 2차원 텐서라고 함

- 3개의 커다란 데이터가 있는데, 각 데이터에는 작은 데이터 4개가 존재

- np.array의 내부에 shape이 다 다르면

    - 예를 들면, 1,2,3,4가 아니라 1,2만 있다면

    - ValueError: Inhomogeneous 에러 발생


### 3차원

In [26]:
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


- 행렬 또는 2차원 텐서를 단위로 한번 더 배열하면 3차원 텐서

    - 3D 텐서라고도 부름

- 0~2차원 첸서는 각각 스칼라, 벡터, 행렬이라고 해도 무방하므로 3차원 이상의 텐서부터 찐 텐서




In [30]:
# NLP에서 3차원 텐서가 쓰이는 예를 보자면
text1 = 'I like NLP'
text2 = 'I like DL'
text3 = 'DL is AI'

# 이제 이 문장들을 One-Hot-Vector화 시켜주면
'''
I = [1 0 0 0 0 0]
like = [0 1 0 0 0]
...
AI = [0 0 0 0 0 1]
'''
# 위의 데이터로 각 문장을 벡터화 시키면 결국 Final Input은
f_oh_vector = np.array([[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]],  
[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]],  
[[0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]]]  )

print('텐서의 차원 :',f_oh_vector.ndim)
print('텐서의 크기(shape) :',f_oh_vector.shape)


텐서의 차원 : 3
텐서의 크기(shape) : (3, 3, 6)


### Keras에서의 텐서

In [33]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
model = Sequential()
# keras에서는 input_shape을 사용하여 신경망의 층에 입력크기를 인자로 줌
# input_shape(input_length,input_dim)
model.add(Dense(256,activation='relu', input_shape=(8,2,10)))
model.add(Dense(10, activation='softmax'))
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 8, 2, 256)         2816      
                                                                 
 dense_4 (Dense)             (None, 8, 2, 10)          2570      
                                                                 
Total params: 5,386
Trainable params: 5,386
Non-trainable params: 0
_________________________________________________________________


### 벡터와 행렬의 연산

In [38]:
# 먼저 요소별 연산(Element-wise)
a = np.array([8,4,5])
b = np.array([1,2,3])
print('두 벡터의 합 :',a+b)
print('두 벡터의 차 :', a-b)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [41]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합: \n', A + B)
print('두 행렬의 차: \n', A - B)

두 행렬의 합: 
 [[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차: 
 [[ 5 14 23 32]
 [49 58 67 76]]


### 백터의 내적과 행렬의 곱셈

In [42]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :',np.dot(A, B))

두 벡터의 내적 : 32


In [44]:
# A의 차원의 개수 == B의 벡터(원소)의 개수
A = np.array([[1, 3],[2, 4],[3,5]])
B = np.array([[5, 7, 9],[6, 8, 10]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31 39]
 [34 46 58]
 [45 61 77]]
